- name: rust-cargo

jobs:
  test:
  runs-on: ubuntu-latest

  steps:
  - uses: actions-rs/cargo@v1.0.1
  - name: Run a build
    run: cargo build --verbose
  - name: Run tests
    run: cargo test --verbose
